version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "production"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cpisnckdik6a"
s3_prefix = "production"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = false
parameter_overrides = "GoogleClientId=\"GoogleClientId\" GoogleClientSecret=\"GoogleClientSecret\""
