version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "production"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18v2v7lr1f3s"
s3_prefix = "production"
region = "eu-west-3"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = ["FastApiLambda=161601479337.dkr.ecr.eu-west-3.amazonaws.com/productionfd89784e/fastapilambdab805af57repo"]
disable_rollback = false
parameter_overrides = "GoogleClientId=\"GoogleClientId\" GoogleClientSecret=\"GoogleClientSecret\""
