AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Screenshot API

  Sample SAM Template for Screenshot API

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: True

Parameters:
    GoogleClientId:
        Description: 'The Google client id'
        Type: "AWS::SSM::Parameter::Value<String>"
        Default: GoogleClientId

    GoogleClientSecret:
        Description: 'The Google client password'
        Type: "AWS::SSM::Parameter::Value<String>"
        Default: GoogleClientSecret

Resources:
  ApiGateWayProxy:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref "AWS::StackName"

  FastApiLambda:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
    Properties:
      PackageType: Image
      Events:
        GateWayProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId: !Ref ApiGateWayProxy
      Environment:
        Variables:
          UserPoolId: !Ref ScreenshotUserPool
          CognitoDomain: !Ref CognitoDomain
          Region: !Ref "AWS::Region"
          StackName: !Ref "AWS::StackName"
          UserTable: !Ref DynamoDB

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: User
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
        -
          AttributeName: "id"
          KeyType: "RANGE"

  SubscriptionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Subscription
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
        -
          AttributeName: "id"
          KeyType: "RANGE"

  ScreenshotUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ScreenshotUserPool
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
          Mutable: true

  GoogleProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      AttributeMapping: {
        "name": "name",
        "family_name": "family_name",
        "email": "email",
        "username": "sub",
      }
      ProviderDetails: {
         "client_id" : !Ref GoogleClientId,
         "client_secret": !Ref GoogleClientSecret,
         "authorize_scopes": "openid profile email",
      }
      ProviderName: Google
      ProviderType: Google
      UserPoolId: !Ref ScreenshotUserPool

  GoogleClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref ScreenshotUserPool
      SupportedIdentityProviders:
        - COGNITO
        - !Ref GoogleProvider
      CallbackURLs:
        - https://jwt.io
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin

  CognitoDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: screenshot
      UserPoolId: !Ref ScreenshotUserPool
